### PR TITLE
Database auth

### PR DESCRIPTION
**Pull request by rideam**
- new environment variables added
  - TOKEN_SIGN - secret string used to sign email verification tokens eg 96e70e4339f77adcbab1356b55fd665
  - AUTH_STATEGY - specify strategy for switching between **db-local** and **file-local** ( defaults to db-local )
  - CONFIRM_URL - url for the confirmation endpoint , used in confirmition email eg http://localhost:3000/app/auth/confirm

- user model migration file `migrations/20220429215904-add_new_user_columns.js`

- both file and db login working side by side on `/app/auth/login` , if AUTH_STATEGY not specified defaults to `db-local`
- signup accessible from the same page 

- After user registers a confirmation email is send to the their email
image

user management implemented on `/app/user/management`
 - accessible from Configuration > Users
 
image

### CODE REVIEW

**Comment by jajukajulz** [comment]
@rideam FYI there is an email config change about to land - see https://github.com/FoodPrintLabs/foodprint/pull/101/files

If you are sending any emails, you will need to:
- update ENV variables 
- import email config `let customSendEmail = require('../config/email/email');`
- create an email template in `config/email` folder and then import it, similar to `let acceptOrderEmail = require('../config/email/orderEmailTemplate');`

**Comment by rideam** [comment]
@jajukajulz okay , it should be relatively easy to switch to that I have a similar config currently in this branch 
image

**Comment by rideam** [comment]
@jajukajulz this PR is ready for you to look at

**Comment by jajukajulz** [comment]
Merging this into trunk in interim.

**Pull request merged**
